name: frontendB_workflow.yml
on:
  push:
    tags:
      - 'v*.*.*'  #run when new tag is pushed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

#      - name: Deploy to S3/ GCP/ Azure
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        run: |
#          aws s3 sync ./dist s3://your-bucket-name/frontendA/ --delete

#      - name: Create Release
#        uses: softprops/action-gh-release@v1
#        with:
#          body: "Release notes for frontendA"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
